# Generated by Django 3.2.16 on 2023-03-12 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellidoPa', models.CharField(max_length=50, verbose_name='Apellido paterno')),
                ('apellidoMa', models.CharField(max_length=50, verbose_name='Apellido materno')),
                ('numAfiliacion', models.CharField(max_length=50, verbose_name='Numero de afiliacion')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('NB', 'No Binario')], max_length=2, verbose_name='Genero')),
                ('nacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('calle', models.CharField(max_length=50, verbose_name='Calle')),
                ('numInt', models.CharField(max_length=50, verbose_name='Numero interior')),
                ('numExt', models.CharField(max_length=50, verbose_name='Numero exterior')),
                ('coloniaLocalidad', models.CharField(choices=[('LA', 'La aldea')], max_length=5, verbose_name='Colonia o localidad')),
                ('idMunicipio', models.CharField(choices=[('1', 'MORELIA')], max_length=5, verbose_name='Municipio')),
                ('idEntidad', models.CharField(choices=[('1', 'Aguascalientes'), ('2', 'Baja California'), ('3', 'Baja California Sur'), ('4', 'Campeche'), ('5', 'Chiapas'), ('6', 'Chihuahua'), ('7', 'Coahuila'), ('8', 'Colima'), ('9', 'Distrito Federal'), ('10', 'Durango'), ('11', 'Guanajuato'), ('12', 'Guerrero'), ('13', 'Hidalgo'), ('14', 'Jalisco'), ('15', 'Michoacán'), ('16', 'Morelos'), ('17', 'Estado de México'), ('18', 'Nayarit'), ('19', 'Nuevo León'), ('20', 'Oaxaca'), ('21', 'Puebla'), ('22', 'Querétaro'), ('23', 'Quintana Roo'), ('24', 'San Luis Potosí'), ('25', 'Sinaloa'), ('26', 'Sonora'), ('27', 'Tabasco'), ('28', 'Tamaulipas'), ('29', 'Tlaxcala'), ('30', 'Veracruz'), ('31', 'Yucatán'), ('32', 'Zacatecas')], max_length=2, verbose_name='Entidad')),
                ('codigoPostal', models.IntegerField(verbose_name='Codigo postal')),
                ('telefonoPaciente', models.CharField(max_length=10, verbose_name='Telefono')),
            ],
        ),
    ]
