# Generated by Django 3.2.16 on 2023-03-15 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='codigoPostal',
            field=models.CharField(max_length=5, verbose_name='Codigo postal'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
