# Generated by Django 3.2.16 on 2023-03-15 17:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0002_auto_20230315_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=50, verbose_name='Clave')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Establecimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=50, verbose_name='Clave')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=50, verbose_name='Clave')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Jurisdiccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=50, verbose_name='Clave')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.entidad')),
            ],
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=50, verbose_name='Clave')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Tipologia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=50, verbose_name='Clave')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
            ],
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='coloniaLocalidad',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='idEntidad',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='idMunicipio',
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claveclues', models.CharField(max_length=50, verbose_name='Clave Clues')),
                ('claveSuave', models.CharField(blank=True, max_length=50, null=True, verbose_name='Clave Suave')),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.establecimiento')),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.institucion')),
                ('localidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.localidad')),
                ('tipologia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.tipologia')),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=50, verbose_name='Clave')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.entidad')),
                ('jurisdiccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.jurisdiccion')),
            ],
        ),
        migrations.AddField(
            model_name='localidad',
            name='municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.municipio'),
        ),
        migrations.CreateModel(
            name='InformacionUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jurisdiccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.jurisdiccion')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.unidad')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='paciente',
            name='entidad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.entidad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='localidad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.localidad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='municipio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.municipio'),
            preserve_default=False,
        ),
    ]
