# Generated by Django 3.2.16 on 2023-03-18 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20230317_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informacionusuario',
            name='unidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.unidad', verbose_name='Unidad'),
        ),
    ]
