# Generated by Django 3.2.16 on 2023-04-24 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_informacionusuario_unidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250)),
                ('logo', models.ImageField(upload_to='media/logos')),
                ('actualizado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
