# Generated by Django 3.2.16 on 2023-04-20 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_informacionusuario_unidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroEstudio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(blank=True, max_length=50, null=True, verbose_name='Folio')),
                ('unidadNot', models.CharField(blank=True, max_length=50, null=True, verbose_name='unidad Notificante')),
                ('local', models.CharField(blank=True, max_length=50, null=True, verbose_name='Localidad')),
                ('entOdEL', models.CharField(blank=True, max_length=50, null=True, verbose_name='Entidad')),
                ('cvClue', models.CharField(blank=True, max_length=50, null=True, verbose_name='claveClue')),
                ('municipio1', models.CharField(blank=True, max_length=50, null=True, verbose_name='Municipio')),
                ('institucion', models.CharField(blank=True, max_length=50, null=True, verbose_name='Institucion')),
                ('cvSuUni', models.CharField(blank=True, max_length=50, null=True, verbose_name='claveSuave')),
                ('jurisdicEq', models.CharField(blank=True, max_length=50, null=True, verbose_name='Jurisdiccion')),
                ('fechaNot', models.CharField(blank=True, max_length=50, null=True, verbose_name='Fecha Notificacion')),
                ('fechaIni', models.CharField(blank=True, max_length=50, null=True, verbose_name='Fecha Inicio Estudio')),
                ('fechaFin', models.CharField(blank=True, max_length=50, null=True, verbose_name='Fecha Fin Estudio')),
                ('DiaProHep', models.CharField(blank=True, max_length=50, null=True, verbose_name='diagnosticoProbable')),
                ('DiaFin', models.CharField(blank=True, max_length=50, null=True, verbose_name='diagnosticoFinal')),
                ('otroDia', models.CharField(blank=True, max_length=50, null=True, verbose_name='otroDiagnostico')),
                ('noAfili', models.CharField(blank=True, max_length=50, null=True, verbose_name='otroDiagnostico')),
                ('nombre', models.CharField(blank=True, max_length=50, null=True, verbose_name='otroDiagnostico')),
                ('ap', models.CharField(blank=True, max_length=50, null=True, verbose_name='otroDiagnostico')),
                ('am', models.CharField(blank=True, max_length=50, null=True, verbose_name='otroDiagnostico')),
                ('sexo', models.CharField(blank=True, max_length=50, null=True, verbose_name='otroDiagnostico')),
                ('fechaNac', models.CharField(blank=True, max_length=50, null=True, verbose_name='otroDiagnostico')),
                ('anos', models.CharField(blank=True, max_length=50, null=True, verbose_name='otroDiagnostico')),
                ('meses', models.CharField(blank=True, max_length=50, null=True, verbose_name='otroDiagnostico')),
                ('dias', models.CharField(blank=True, max_length=50, null=True, verbose_name='otroDiagnostico')),
                ('calle', models.CharField(blank=True, max_length=50, null=True, verbose_name='otroDiagnostico')),
                ('num', models.CharField(blank=True, max_length=50, null=True, verbose_name='otroDiagnostico')),
                ('colonia', models.CharField(blank=True, max_length=50, null=True, verbose_name='otroDiagnostico')),
                ('municipio2', models.CharField(blank=True, max_length=50, null=True, verbose_name='otroDiagnostico')),
                ('cvMun2', models.CharField(blank=True, max_length=50, null=True, verbose_name='otroDiagnostico')),
                ('ent2', models.CharField(blank=True, max_length=50, null=True, verbose_name='otroDiagnostico')),
                ('cvEnt2', models.CharField(blank=True, max_length=50, null=True, verbose_name='otroDiagnostico')),
                ('cp2', models.CharField(blank=True, max_length=50, null=True, verbose_name='otroDiagnostico')),
                ('tel2', models.CharField(blank=True, max_length=50, null=True, verbose_name='otroDiagnostico')),
                ('fechaIn3', models.CharField(blank=True, max_length=50, null=True, verbose_name='otroDiagnostico')),
                ('signoSint3', models.CharField(blank=True, max_length=50, null=True, verbose_name='otroDiagnostico')),
                ('tratamiento3', models.CharField(blank=True, max_length=50, null=True, verbose_name='otroDiagnostico')),
            ],
        ),
    ]
