# Generated by Django 3.2.16 on 2023-04-25 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_logos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logos',
            name='logo',
            field=models.ImageField(null=True, upload_to='media/logos'),
        ),
        migrations.CreateModel(
            name='LogosImagen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='media/logos')),
                ('logoIma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.logos')),
            ],
        ),
    ]
