# Generated by Django 3.2.16 on 2023-04-23 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_paciente_numafiliacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidad',
            name='clave',
            field=models.CharField(max_length=50, unique=True, verbose_name='Clave'),
        ),
        migrations.AlterField(
            model_name='establecimiento',
            name='clave',
            field=models.CharField(max_length=50, unique=True, verbose_name='Clave'),
        ),
        migrations.AlterField(
            model_name='institucion',
            name='clave',
            field=models.CharField(max_length=50, unique=True, verbose_name='Clave'),
        ),
        migrations.AlterField(
            model_name='jurisdiccion',
            name='clave',
            field=models.CharField(max_length=50, unique=True, verbose_name='Clave'),
        ),
        migrations.AlterField(
            model_name='localidad',
            name='clave',
            field=models.CharField(max_length=50, unique=True, verbose_name='Clave'),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='clave',
            field=models.CharField(max_length=50, unique=True, verbose_name='Clave'),
        ),
        migrations.AlterField(
            model_name='registroestudio',
            name='folio',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Folio'),
        ),
        migrations.AlterField(
            model_name='tipologia',
            name='clave',
            field=models.CharField(max_length=50, unique=True, verbose_name='Clave'),
        ),
        migrations.AlterField(
            model_name='unidad',
            name='claveSuave',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Clave Suave'),
        ),
        migrations.AlterField(
            model_name='unidad',
            name='claveclues',
            field=models.CharField(max_length=50, unique=True, verbose_name='Clave Clues'),
        ),
    ]
