# Generated by Django 3.2.16 on 2023-04-23 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20230423_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localidad',
            name='municipio',
        ),
        migrations.RemoveField(
            model_name='municipio',
            name='jurisdiccion',
        ),
        migrations.AddField(
            model_name='unidad',
            name='jurisdiccion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.jurisdiccion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unidad',
            name='municipio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.municipio'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Estudio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50, null=True, verbose_name='otroDiagnostico')),
                ('tipo', models.CharField(blank=True, max_length=50, null=True, verbose_name='otroDiagnostico')),
                ('fecha', models.CharField(blank=True, max_length=50, null=True, verbose_name='otroDiagnostico')),
                ('resultado', models.CharField(blank=True, max_length=50, null=True, verbose_name='otroDiagnostico')),
                ('registroEstudio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.registroestudio')),
            ],
        ),
    ]
