# Generated by Django 3.2.16 on 2023-04-27 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_logos'),
        ('home', '0011_alter_localidad_clave'),
    ]

    operations = [
    ]
