# Generated by Django 3.2.16 on 2023-04-28 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_merge_0007_logos_0011_alter_localidad_clave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logos',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='ImagenLogo'),
        ),
    ]
