# Generated by Django 3.2.16 on 2023-04-28 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_logos_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacionBrote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Folio')),
                ('unidadNot', models.CharField(blank=True, max_length=50, null=True, verbose_name='unidad Notificante')),
                ('local', models.CharField(blank=True, max_length=50, null=True, verbose_name='Localidad')),
                ('entOdEL', models.CharField(blank=True, max_length=50, null=True, verbose_name='Entidad')),
                ('cvClue', models.CharField(blank=True, max_length=50, null=True, verbose_name='claveClue')),
                ('municipio1', models.CharField(blank=True, max_length=50, null=True, verbose_name='Municipio')),
                ('institucion', models.CharField(blank=True, max_length=50, null=True, verbose_name='Institucion')),
                ('fechaNot', models.CharField(blank=True, max_length=50, null=True, verbose_name='Fecha Notificacion')),
                ('fechaEstudio', models.CharField(blank=True, max_length=50, null=True, verbose_name='Fecha Fin Estudio')),
                ('DiaProHep', models.CharField(blank=True, max_length=50, null=True, verbose_name='diagnosticoProbable')),
                ('DiaFin', models.CharField(blank=True, max_length=50, null=True, verbose_name='diagnosticoFinal')),
                ('DiaProHep2', models.CharField(blank=True, max_length=50, null=True, verbose_name='diagnosticoProbable')),
                ('DiaFin2', models.CharField(blank=True, max_length=50, null=True, verbose_name='diagnosticoFinal')),
                ('fechaNot2', models.CharField(blank=True, max_length=50, null=True, verbose_name='Fecha Notificacion')),
                ('fechaNot3', models.CharField(blank=True, max_length=50, null=True, verbose_name='Fecha Notificacion')),
                ('casosProbables', models.CharField(blank=True, max_length=50, null=True, verbose_name='Fecha Notificacion')),
                ('casosConfirmados', models.CharField(blank=True, max_length=50, null=True, verbose_name='Fecha Notificacion')),
                ('hospitalizados', models.CharField(blank=True, max_length=50, null=True, verbose_name='Fecha Notificacion')),
                ('anteEpiBrote', models.CharField(blank=True, max_length=50, null=True, verbose_name='Fecha Notificacion')),
                ('probFuenBrote', models.CharField(blank=True, max_length=50, null=True, verbose_name='Fecha Notificacion')),
                ('probMecTransmision', models.CharField(blank=True, max_length=50, null=True, verbose_name='Fecha Notificacion')),
                ('accionesPrevControl', models.CharField(blank=True, max_length=50, null=True, verbose_name='Fecha Notificacion')),
            ],
        ),
        migrations.CreateModel(
            name='DistribucionGeografica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(blank=True, max_length=50, null=True, verbose_name='diagnosticoProbable')),
                ('manzana', models.CharField(blank=True, max_length=50, null=True, verbose_name='diagnosticoFinal')),
                ('colonia', models.CharField(blank=True, max_length=50, null=True, verbose_name='Fecha Notificacion')),
                ('localidad', models.CharField(blank=True, max_length=50, null=True, verbose_name='Fecha Notificacion')),
                ('escuela', models.CharField(blank=True, max_length=50, null=True, verbose_name='Fecha Notificacion')),
                ('guardeOvivienda', models.CharField(blank=True, max_length=50, null=True, verbose_name='Fecha Notificacion')),
                ('numeroCasos', models.CharField(blank=True, max_length=50, null=True, verbose_name='Fecha Notificacion')),
                ('numeroDefunciones', models.CharField(blank=True, max_length=50, null=True, verbose_name='Fecha Notificacion')),
                ('notificacionBrote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.notificacionbrote')),
            ],
        ),
    ]
