# Generated by Django 3.2.16 on 2023-05-02 02:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_distribuciongeografica_notificacionbrote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distribuciongeografica',
            name='colonia',
        ),
        migrations.RemoveField(
            model_name='distribuciongeografica',
            name='escuela',
        ),
        migrations.RemoveField(
            model_name='distribuciongeografica',
            name='guardeOvivienda',
        ),
        migrations.RemoveField(
            model_name='distribuciongeografica',
            name='localidad',
        ),
        migrations.RemoveField(
            model_name='distribuciongeografica',
            name='manzana',
        ),
        migrations.RemoveField(
            model_name='registroestudio',
            name='am',
        ),
        migrations.RemoveField(
            model_name='registroestudio',
            name='anos',
        ),
        migrations.RemoveField(
            model_name='registroestudio',
            name='ap',
        ),
        migrations.RemoveField(
            model_name='registroestudio',
            name='calle',
        ),
        migrations.RemoveField(
            model_name='registroestudio',
            name='colonia',
        ),
        migrations.RemoveField(
            model_name='registroestudio',
            name='cp2',
        ),
        migrations.RemoveField(
            model_name='registroestudio',
            name='cvClue',
        ),
        migrations.RemoveField(
            model_name='registroestudio',
            name='cvEnt2',
        ),
        migrations.RemoveField(
            model_name='registroestudio',
            name='cvMun2',
        ),
        migrations.RemoveField(
            model_name='registroestudio',
            name='cvSuUni',
        ),
        migrations.RemoveField(
            model_name='registroestudio',
            name='dias',
        ),
        migrations.RemoveField(
            model_name='registroestudio',
            name='ent2',
        ),
        migrations.RemoveField(
            model_name='registroestudio',
            name='entOdEL',
        ),
        migrations.RemoveField(
            model_name='registroestudio',
            name='fechaNac',
        ),
        migrations.RemoveField(
            model_name='registroestudio',
            name='institucion',
        ),
        migrations.RemoveField(
            model_name='registroestudio',
            name='jurisdicEq',
        ),
        migrations.RemoveField(
            model_name='registroestudio',
            name='local',
        ),
        migrations.RemoveField(
            model_name='registroestudio',
            name='meses',
        ),
        migrations.RemoveField(
            model_name='registroestudio',
            name='municipio1',
        ),
        migrations.RemoveField(
            model_name='registroestudio',
            name='municipio2',
        ),
        migrations.RemoveField(
            model_name='registroestudio',
            name='noAfili',
        ),
        migrations.RemoveField(
            model_name='registroestudio',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='registroestudio',
            name='num',
        ),
        migrations.RemoveField(
            model_name='registroestudio',
            name='sexo',
        ),
        migrations.RemoveField(
            model_name='registroestudio',
            name='tel2',
        ),
        migrations.AddField(
            model_name='registroestudio',
            name='boolFinalizado',
            field=models.BooleanField(default=False, verbose_name='Finalizado'),
        ),
        migrations.AddField(
            model_name='registroestudio',
            name='boolLab',
            field=models.BooleanField(default=False, verbose_name='Ya se registro laboratorio'),
        ),
        migrations.AddField(
            model_name='registroestudio',
            name='edadAnio',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Edad (años)'),
        ),
        migrations.AddField(
            model_name='registroestudio',
            name='edadDia',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Edad (días)'),
        ),
        migrations.AddField(
            model_name='registroestudio',
            name='edadMes',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Edad (meses)'),
        ),
        migrations.AddField(
            model_name='registroestudio',
            name='llegadaProc',
            field=models.DateField(blank=True, null=True, verbose_name='Llegada de procedencia'),
        ),
        migrations.AddField(
            model_name='registroestudio',
            name='localidadProc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.localidad'),
        ),
        migrations.AddField(
            model_name='registroestudio',
            name='municipioProc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.municipio'),
        ),
        migrations.AddField(
            model_name='registroestudio',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.paciente', verbose_name='Paciente'),
        ),
        migrations.AddField(
            model_name='registroestudio',
            name='procedencia',
            field=models.CharField(blank=True, choices=[('local', 'Local'), ('importado', 'Importado')], max_length=10, null=True, verbose_name='Procedencia'),
        ),
        migrations.AddField(
            model_name='registroestudio',
            name='salidaProc',
            field=models.DateField(blank=True, null=True, verbose_name='Salida de procedencia'),
        ),
        migrations.AlterField(
            model_name='distribuciongeografica',
            name='area',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Área, Manzana, Colonia, Localidad, Escuela, Guardería O Vivienda'),
        ),
        migrations.AlterField(
            model_name='registroestudio',
            name='DiaFin',
            field=models.CharField(blank=True, choices=[('A', 'Hepatitis A'), ('B', 'Hepatitis B'), ('C', 'Hepatitis C'), ('D', 'Hepatitis D'), ('E', 'Hepatitis E')], max_length=1, null=True, verbose_name='Diagnóstico Final'),
        ),
        migrations.AlterField(
            model_name='registroestudio',
            name='DiaProHep',
            field=models.CharField(choices=[('A', 'Hepatitis A'), ('B', 'Hepatitis B'), ('C', 'Hepatitis C'), ('D', 'Hepatitis D'), ('E', 'Hepatitis E')], max_length=1, verbose_name='Diagnóstico Probable'),
        ),
        migrations.AlterField(
            model_name='registroestudio',
            name='fechaFin',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Fin Estudio'),
        ),
        migrations.AlterField(
            model_name='registroestudio',
            name='fechaIn3',
            field=models.DateField(verbose_name='Fecha inicio de signos'),
        ),
        migrations.AlterField(
            model_name='registroestudio',
            name='fechaIni',
            field=models.DateField(verbose_name='Fecha Inicio Estudio'),
        ),
        migrations.AlterField(
            model_name='registroestudio',
            name='fechaNot',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha Notificacion'),
        ),
        migrations.AlterField(
            model_name='registroestudio',
            name='otroDia',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Otro Diagnóstico'),
        ),
        migrations.AlterField(
            model_name='registroestudio',
            name='signoSint3',
            field=models.TextField(verbose_name='Signos y sintomas'),
        ),
        migrations.AlterField(
            model_name='registroestudio',
            name='tratamiento3',
            field=models.TextField(verbose_name='Tratamiento'),
        ),
        migrations.AlterField(
            model_name='registroestudio',
            name='unidadNot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.unidad', verbose_name='Unidad notificante'),
        ),
    ]
