# Generated by Django 3.2.16 on 2023-05-03 05:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20230501_2048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificacionbrote',
            name='cvClue',
        ),
        migrations.RemoveField(
            model_name='notificacionbrote',
            name='entOdEL',
        ),
        migrations.RemoveField(
            model_name='notificacionbrote',
            name='institucion',
        ),
        migrations.RemoveField(
            model_name='notificacionbrote',
            name='local',
        ),
        migrations.RemoveField(
            model_name='notificacionbrote',
            name='municipio1',
        ),
        migrations.AlterField(
            model_name='notificacionbrote',
            name='DiaFin',
            field=models.CharField(blank=True, choices=[('A', 'Hepatitis A'), ('B', 'Hepatitis B'), ('C', 'Hepatitis C'), ('D', 'Hepatitis D'), ('E', 'Hepatitis E')], max_length=1, null=True, verbose_name='Diagnóstico Final'),
        ),
        migrations.AlterField(
            model_name='notificacionbrote',
            name='DiaFin2',
            field=models.CharField(blank=True, choices=[('A', 'Hepatitis A'), ('B', 'Hepatitis B'), ('C', 'Hepatitis C'), ('D', 'Hepatitis D'), ('E', 'Hepatitis E')], max_length=1, null=True, verbose_name='Diagnóstico Final'),
        ),
        migrations.AlterField(
            model_name='notificacionbrote',
            name='DiaProHep',
            field=models.CharField(blank=True, choices=[('A', 'Hepatitis A'), ('B', 'Hepatitis B'), ('C', 'Hepatitis C'), ('D', 'Hepatitis D'), ('E', 'Hepatitis E')], max_length=1, null=True, verbose_name='Diagnóstico Probable'),
        ),
        migrations.AlterField(
            model_name='notificacionbrote',
            name='DiaProHep2',
            field=models.CharField(blank=True, choices=[('A', 'Hepatitis A'), ('B', 'Hepatitis B'), ('C', 'Hepatitis C'), ('D', 'Hepatitis D'), ('E', 'Hepatitis E')], max_length=1, null=True, verbose_name='Diagnóstico Probable'),
        ),
        migrations.AlterField(
            model_name='notificacionbrote',
            name='fechaEstudio',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Inicio Estudio'),
        ),
        migrations.AlterField(
            model_name='notificacionbrote',
            name='fechaNot',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha Notificacion'),
        ),
        migrations.AlterField(
            model_name='notificacionbrote',
            name='fechaNot2',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha Notificacion'),
        ),
        migrations.AlterField(
            model_name='notificacionbrote',
            name='fechaNot3',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha Notificacion'),
        ),
        migrations.AlterField(
            model_name='notificacionbrote',
            name='unidadNot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.unidad', verbose_name='Unidad notificante'),
        ),
        migrations.AlterField(
            model_name='registroestudio',
            name='DiaProHep',
            field=models.CharField(blank=True, choices=[('A', 'Hepatitis A'), ('B', 'Hepatitis B'), ('C', 'Hepatitis C'), ('D', 'Hepatitis D'), ('E', 'Hepatitis E')], max_length=1, null=True, verbose_name='Diagnóstico Probable'),
        ),
    ]
