# Generated by Django 3.2.16 on 2023-05-03 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20230502_2338'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anexo8',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaDefuncion', models.DateField(blank=True, null=True, verbose_name='Fecha de defunción')),
                ('escolaridad', models.CharField(blank=True, choices=[('1', 'Ninguna'), ('2', 'Preescolar'), ('3', 'Primaria Incompleta'), ('4', 'Primaria Completa'), ('5', 'Secundaria Incompleta'), ('6', 'Secundaria Completa'), ('7', 'Preparatoria Incompleta'), ('8', 'Preparatoria Completa'), ('9', 'Profesional'), ('10', 'Posgrado'), ('11', 'Se ignora')], max_length=10, null=True, verbose_name='Escolaridad')),
                ('ocupacion', models.CharField(blank=True, max_length=30, null=True, verbose_name='Ocupación')),
                ('nombreCertificante', models.CharField(max_length=20, verbose_name='Nombre del Certificante')),
                ('causasDef', models.CharField(max_length=200, verbose_name='Causas de defunción')),
                ('causasDef2', models.CharField(max_length=100, verbose_name='Causas de defunción2')),
                ('causaVigEpi', models.CharField(max_length=100, verbose_name='Causa sujeta a vigilancia epidemiologica')),
                ('ratifica', models.CharField(blank=True, choices=[('1', 'Ratifica'), ('2', 'Rectifica')], max_length=100, null=True, verbose_name='Ratifica')),
                ('causaVigEpi2', models.CharField(max_length=100, verbose_name='Causa sujeta a vigilancia epidemiologica')),
                ('causasDef3', models.CharField(max_length=200, verbose_name='Causas de defunción3')),
                ('causasDef4', models.CharField(max_length=100, verbose_name='Causas de defunción4')),
                ('fechaRecolección', models.DateField(blank=True, null=True, verbose_name='Fecha de recolección')),
                ('fechaInicio', models.DateField(blank=True, null=True, verbose_name='Fecha de inicio')),
                ('fechaConclusion', models.DateField(blank=True, null=True, verbose_name='Fecha de conclusión')),
                ('reporteInegi', models.DateField(blank=True, null=True, verbose_name='Fecha de reporte a INEGI')),
                ('observaciones', models.CharField(blank=True, max_length=200, null=True, verbose_name='Observaciones')),
                ('nombreResponsableInv', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre del responsable de la investigación')),
                ('cargo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Cargo')),
                ('firma', models.ImageField(blank=True, null=True, upload_to='firmas/', verbose_name='Firma')),
                ('tipoDocumento', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de documento')),
                ('numPaquete', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de paquete')),
                ('numActa', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de acta')),
                ('folioCaptura', models.CharField(blank=True, max_length=50, null=True, verbose_name='Folio de captura')),
                ('nombreCodificador', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre del codificador')),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.institucion')),
                ('lugarDefEnti', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entidadDef', to='home.municipio')),
                ('lugarDefMuni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='municipioDef', to='home.municipio')),
                ('lugardeResidenciaEnti', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.entidad')),
                ('lugardeResidenciaMuni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.municipio')),
                ('nombreFallecido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.paciente')),
            ],
        ),
    ]
