# Generated by Django 3.2.16 on 2023-05-03 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_anexo8'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anexo8',
            name='firma',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Firma'),
        ),
        migrations.AlterField(
            model_name='anexo8',
            name='lugarDefEnti',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entidadDef', to='home.entidad'),
        ),
    ]
