# Generated by Django 3.2.16 on 2023-05-04 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20230503_1200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anexo8',
            old_name='fechaRecolección',
            new_name='fechaRecoleccion',
        ),
    ]
