# Generated by Django 3.2.16 on 2023-05-11 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_rename_fecharecolección_anexo8_fecharecoleccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroestudio',
            name='aerea',
            field=models.CharField(choices=[('investigada', 'Investigada'), ('confirmada', 'Confirmada'), ('ninguna', 'Ninguna')], default='investigada', max_length=20, verbose_name='Aerea'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registroestudio',
            name='agua',
            field=models.CharField(choices=[('investigada', 'Investigada'), ('confirmada', 'Confirmada'), ('ninguna', 'Ninguna')], default='investigada', max_length=20, verbose_name='Agua'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registroestudio',
            name='alimentos',
            field=models.CharField(choices=[('investigada', 'Investigada'), ('confirmada', 'Confirmada'), ('ninguna', 'Ninguna')], default='investigada', max_length=20, verbose_name='Alimentos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registroestudio',
            name='animales',
            field=models.CharField(choices=[('investigada', 'Investigada'), ('confirmada', 'Confirmada'), ('ninguna', 'Ninguna')], default='investigada', max_length=20, verbose_name='Animales'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registroestudio',
            name='digestiva',
            field=models.CharField(choices=[('investigada', 'Investigada'), ('confirmada', 'Confirmada'), ('ninguna', 'Ninguna')], default='investigada', max_length=20, verbose_name='Digestiva'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registroestudio',
            name='fomites',
            field=models.CharField(choices=[('investigada', 'Investigada'), ('confirmada', 'Confirmada'), ('ninguna', 'Ninguna')], default='investigada', max_length=20, verbose_name='Fomites'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registroestudio',
            name='fomitesMec',
            field=models.CharField(choices=[('investigada', 'Investigada'), ('confirmada', 'Confirmada'), ('ninguna', 'Ninguna')], default='investigada', max_length=20, verbose_name='Fomites'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registroestudio',
            name='otraPersona',
            field=models.CharField(choices=[('investigada', 'Investigada'), ('confirmada', 'Confirmada'), ('ninguna', 'Ninguna')], default='investigada', max_length=20, verbose_name='Otra persona'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registroestudio',
            name='otrosFuentes',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Otras fuentes'),
        ),
        migrations.AddField(
            model_name='registroestudio',
            name='otrosMecanismos',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Otras mecanismos'),
        ),
        migrations.AddField(
            model_name='registroestudio',
            name='personaPersona',
            field=models.CharField(choices=[('investigada', 'Investigada'), ('confirmada', 'Confirmada'), ('ninguna', 'Ninguna')], default='investigada', max_length=20, verbose_name='Persona a persona'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registroestudio',
            name='vectores',
            field=models.CharField(choices=[('investigada', 'Investigada'), ('confirmada', 'Confirmada'), ('ninguna', 'Ninguna')], default='investigada', max_length=20, verbose_name='Vectores'),
            preserve_default=False,
        ),
    ]
