# Generated by Django 3.2.16 on 2023-05-12 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20230511_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroestudio',
            name='otrosFuentes',
            field=models.TextField(blank=True, null=True, verbose_name='Otras fuentes'),
        ),
        migrations.AlterField(
            model_name='registroestudio',
            name='otrosMecanismos',
            field=models.TextField(blank=True, null=True, verbose_name='Otras mecanismos'),
        ),
    ]
