# Generated by Django 3.2.16 on 2023-05-15 02:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_auto_20230511_2144'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('domicilio', models.CharField(max_length=100, verbose_name='Domicilio')),
                ('edad', models.SmallIntegerField(verbose_name='Edad')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=10, verbose_name='Sexo')),
                ('contacto', models.CharField(choices=[('I', 'Intradomiciliario'), ('E', 'Extradomiciliario')], max_length=20, verbose_name='Sexo')),
                ('caso', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=2, verbose_name='Caso')),
            ],
        ),
        migrations.RemoveField(
            model_name='registroestudio',
            name='boolFinalizado',
        ),
        migrations.AddField(
            model_name='registroestudio',
            name='accionesMedidas',
            field=models.TextField(default='', verbose_name='Acciones y medidas de control'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registroestudio',
            name='cloracion',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='No', max_length=2, verbose_name='Cloracion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registroestudio',
            name='comentariosConclusiones',
            field=models.TextField(default='', verbose_name='Comentarios y conclusion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registroestudio',
            name='estado',
            field=models.CharField(choices=[('Tiempo1', 'Tiempo1'), ('Tiempo2', 'Tiempo2'), ('Finalizado', 'Finalizado')], default='Tiempo1', max_length=30, verbose_name='Estado del formulario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registroestudio',
            name='fallecio',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='No', max_length=2, verbose_name='Fallecio?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registroestudio',
            name='fechaCap',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha Captura'),
        ),
        migrations.AddField(
            model_name='registroestudio',
            name='fechaDefuncion',
            field=models.DateField(blank=True, null=True, verbose_name='Salida de procedencia'),
        ),
        migrations.AddField(
            model_name='registroestudio',
            name='letrinizacion',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='No', max_length=2, verbose_name='Letrinizacion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registroestudio',
            name='numCloracion',
            field=models.IntegerField(default=0, verbose_name='Numero cloracion'),
        ),
        migrations.AddField(
            model_name='registroestudio',
            name='numLetrinizacion',
            field=models.IntegerField(default=0, verbose_name='Numero letrinizacion'),
        ),
        migrations.AddField(
            model_name='registroestudio',
            name='numPlaticas',
            field=models.IntegerField(default=0, verbose_name='Numero platicas'),
        ),
        migrations.AddField(
            model_name='registroestudio',
            name='numTratamientosFam',
            field=models.IntegerField(default=0, verbose_name='Numero tratamientos familiares'),
        ),
        migrations.AddField(
            model_name='registroestudio',
            name='numTratamientosInd',
            field=models.IntegerField(default=0, verbose_name='Numero tratamientos individuales'),
        ),
        migrations.AddField(
            model_name='registroestudio',
            name='numVacunacion',
            field=models.IntegerField(default=0, verbose_name='Numero vacunacion'),
        ),
        migrations.AddField(
            model_name='registroestudio',
            name='otrasActividades',
            field=models.TextField(default='', verbose_name='Otras actividades'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registroestudio',
            name='perdioCaso',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='No', max_length=2, verbose_name='Se perdio el caso?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registroestudio',
            name='platicas',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='No', max_length=2, verbose_name='Platicas de fomentos para la salud'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registroestudio',
            name='portador',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='No', max_length=2, verbose_name='Quedo como portador?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registroestudio',
            name='reestablecer',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='No', max_length=2, verbose_name='Se reestablecio integrante?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registroestudio',
            name='secuelas',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='No', max_length=2, verbose_name='Quedo secuelas?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registroestudio',
            name='tratamientosFam',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='No', max_length=2, verbose_name='Tratamientos familiares'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registroestudio',
            name='tratamientosInd',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='No', max_length=2, verbose_name='Tratamientos individuales'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registroestudio',
            name='vacunacion',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='No', max_length=2, verbose_name='Vacunacion'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='estudio',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='estudio',
            name='nombre',
            field=models.CharField(default='', max_length=100, verbose_name='Nombre de estudio'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='estudio',
            name='resultado',
            field=models.CharField(default='Negativo', max_length=100, verbose_name='Resultado'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='estudio',
            name='tipo',
            field=models.CharField(choices=[('PR', 'Preliminar'), ('CF', 'Confirmatorio'), ('CT', 'Control')], default='PR', max_length=2, verbose_name='Tipo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paciente',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=2, verbose_name='Genero'),
        ),
        migrations.AlterField(
            model_name='registroestudio',
            name='aerea',
            field=models.CharField(choices=[('Investigada', 'Investigada'), ('Confirmada', 'Confirmada'), ('Ninguna', 'Ninguna')], max_length=20, verbose_name='Aerea'),
        ),
        migrations.AlterField(
            model_name='registroestudio',
            name='agua',
            field=models.CharField(choices=[('Investigada', 'Investigada'), ('Confirmada', 'Confirmada'), ('Ninguna', 'Ninguna')], max_length=20, verbose_name='Agua'),
        ),
        migrations.AlterField(
            model_name='registroestudio',
            name='alimentos',
            field=models.CharField(choices=[('Investigada', 'Investigada'), ('Confirmada', 'Confirmada'), ('Ninguna', 'Ninguna')], max_length=20, verbose_name='Alimentos'),
        ),
        migrations.AlterField(
            model_name='registroestudio',
            name='animales',
            field=models.CharField(choices=[('Investigada', 'Investigada'), ('Confirmada', 'Confirmada'), ('Ninguna', 'Ninguna')], max_length=20, verbose_name='Animales'),
        ),
        migrations.AlterField(
            model_name='registroestudio',
            name='digestiva',
            field=models.CharField(choices=[('Investigada', 'Investigada'), ('Confirmada', 'Confirmada'), ('Ninguna', 'Ninguna')], max_length=20, verbose_name='Digestiva'),
        ),
        migrations.AlterField(
            model_name='registroestudio',
            name='fomites',
            field=models.CharField(choices=[('Investigada', 'Investigada'), ('Confirmada', 'Confirmada'), ('Ninguna', 'Ninguna')], max_length=20, verbose_name='Fomites'),
        ),
        migrations.AlterField(
            model_name='registroestudio',
            name='fomitesMec',
            field=models.CharField(choices=[('Investigada', 'Investigada'), ('Confirmada', 'Confirmada'), ('Ninguna', 'Ninguna')], max_length=20, verbose_name='Fomites'),
        ),
        migrations.AlterField(
            model_name='registroestudio',
            name='otraPersona',
            field=models.CharField(choices=[('Investigada', 'Investigada'), ('Confirmada', 'Confirmada'), ('Ninguna', 'Ninguna')], max_length=20, verbose_name='Otra persona'),
        ),
        migrations.AlterField(
            model_name='registroestudio',
            name='personaPersona',
            field=models.CharField(choices=[('Investigada', 'Investigada'), ('Confirmada', 'Confirmada'), ('Ninguna', 'Ninguna')], max_length=20, verbose_name='Persona a persona'),
        ),
        migrations.AlterField(
            model_name='registroestudio',
            name='procedencia',
            field=models.CharField(blank=True, choices=[('Local', 'Local'), ('Importado', 'Importado')], max_length=10, null=True, verbose_name='Procedencia'),
        ),
        migrations.AlterField(
            model_name='registroestudio',
            name='vectores',
            field=models.CharField(choices=[('Investigada', 'Investigada'), ('Confirmada', 'Confirmada'), ('Ninguna', 'Ninguna')], max_length=20, verbose_name='Vectores'),
        ),
    ]
