# Generated by Django 3.2.16 on 2023-05-23 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_auto_20230516_2232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anexo8',
            name='causasDef',
        ),
        migrations.RemoveField(
            model_name='anexo8',
            name='causasDef2',
        ),
        migrations.RemoveField(
            model_name='anexo8',
            name='causasDef3',
        ),
        migrations.RemoveField(
            model_name='anexo8',
            name='causasDef4',
        ),
        migrations.RemoveField(
            model_name='anexo8',
            name='institucion',
        ),
        migrations.AddField(
            model_name='anexo8',
            name='afiliacionServicios',
            field=models.CharField(choices=[('NINGUNA', 'NINGUNA'), ('ISSSTE', 'ISSSTE'), ('SEDENA', 'SEDENA'), ('OTRA', 'OTRA'), ('SE IGNORA', 'SE IGNORA'), ('IMSS', 'IMSS'), ('PEMEX', 'PEMEX'), ('SEMAR', 'SEMAR'), ('IMSS BIENESTAR', 'IMSS BIENESTAR')], default='NINGUNA', max_length=20, verbose_name='Afiliacion de Servicios Medicos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anexo8',
            name='apellidoMaResponsableInv',
            field=models.CharField(default='', max_length=50, verbose_name='Apellido materno del responsable de la investigación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anexo8',
            name='apellidoPaResponsableInv',
            field=models.CharField(default='', max_length=50, verbose_name='Apellido paterno del responsable de la investigación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anexo8',
            name='causaBasica2I',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Causas de defunción 2 I (1) Causa Basica'),
        ),
        migrations.AddField(
            model_name='anexo8',
            name='causaBasicaI',
            field=models.CharField(default='', max_length=100, verbose_name='Causas de defunción I (1) Causa Basica'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anexo8',
            name='causaDefCodigoCi22I',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Causas de defunción 2 I (1) Codigo CIE'),
        ),
        migrations.AddField(
            model_name='anexo8',
            name='causaDefCodigoCie2I2',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Causas de defunción 2 I (2) Codigo CIE'),
        ),
        migrations.AddField(
            model_name='anexo8',
            name='causaDefCodigoCie2I3',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Causas de defunción 2 I (3) Codigo CIE'),
        ),
        migrations.AddField(
            model_name='anexo8',
            name='causaDefCodigoCie2I4',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Causas de defunción 2 I (4) Codigo CIE'),
        ),
        migrations.AddField(
            model_name='anexo8',
            name='causaDefCodigoCie2II1',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Causas de defunción 2 II (1) Codigo CIE'),
        ),
        migrations.AddField(
            model_name='anexo8',
            name='causaDefCodigoCie2II2',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Causas de defunción 2 II (2) Codigo CIE'),
        ),
        migrations.AddField(
            model_name='anexo8',
            name='causaDefCodigoCieI',
            field=models.CharField(default='', max_length=4, verbose_name='Causas de defunción I (1) Codigo CIE'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anexo8',
            name='causaDefCodigoCieI2',
            field=models.CharField(default='', max_length=4, verbose_name='Causas de defunción I (2) Codigo CIE'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anexo8',
            name='causaDefCodigoCieI3',
            field=models.CharField(default='', max_length=4, verbose_name='Causas de defunción I (3) Codigo CIE'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anexo8',
            name='causaDefCodigoCieI4',
            field=models.CharField(default='', max_length=4, verbose_name='Causas de defunción I (4) Codigo CIE'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anexo8',
            name='causaDefCodigoCieII1',
            field=models.CharField(default='', max_length=4, verbose_name='Causas de defunción II (1) Codigo CIE'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anexo8',
            name='causaDefCodigoCieII2',
            field=models.CharField(default='', max_length=4, verbose_name='Causas de defunción II (2) Codigo CIE'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anexo8',
            name='causaDefInter2I',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Causas de defunción 2 I (1) Intervalo'),
        ),
        migrations.AddField(
            model_name='anexo8',
            name='causaDefInter2I2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Causas de defunción 2 I (2) Intervalo'),
        ),
        migrations.AddField(
            model_name='anexo8',
            name='causaDefInter2I3',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Causas de defunción 2 I (3) Intervalo'),
        ),
        migrations.AddField(
            model_name='anexo8',
            name='causaDefInter2I4',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Causas de defunción 2 I (4) Intervalo'),
        ),
        migrations.AddField(
            model_name='anexo8',
            name='causaDefInter2II1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Causas de defunción 2 II (1) Intervalo'),
        ),
        migrations.AddField(
            model_name='anexo8',
            name='causaDefInter2II2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Causas de defunción 2 II (2) Intervalo'),
        ),
        migrations.AddField(
            model_name='anexo8',
            name='causaDefInterI',
            field=models.CharField(default='', max_length=100, verbose_name='Causas de defunción I (1) Intervalo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anexo8',
            name='causaDefInterI2',
            field=models.CharField(default='', max_length=100, verbose_name='Causas de defunción I (2) Intervalo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anexo8',
            name='causaDefInterI3',
            field=models.CharField(default='', max_length=100, verbose_name='Causas de defunción I (3) Intervalo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anexo8',
            name='causaDefInterI4',
            field=models.CharField(default='', max_length=100, verbose_name='Causas de defunción I (4) Intervalo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anexo8',
            name='causaDefInterII1',
            field=models.CharField(default='', max_length=100, verbose_name='Causas de defunción II (1) Intervalo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anexo8',
            name='causaDefInterII2',
            field=models.CharField(default='', max_length=100, verbose_name='Causas de defunción II (2) Intervalo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anexo8',
            name='causaVigEpiCodigoCie',
            field=models.CharField(default='', max_length=4, verbose_name='Causa sujeta a vigilancia epidemiologica, Codigo CIE'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anexo8',
            name='causaVigEpiCodigoCie2',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Causa sujeta a vigilancia epidemiologica 2, Codigo CIE'),
        ),
        migrations.AddField(
            model_name='anexo8',
            name='causasDef2I',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Causas de defunción 2 I (1)'),
        ),
        migrations.AddField(
            model_name='anexo8',
            name='causasDef2I2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Causas de defunción 2 I (2)'),
        ),
        migrations.AddField(
            model_name='anexo8',
            name='causasDef2I3',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Causas de defunción 2 I (3)'),
        ),
        migrations.AddField(
            model_name='anexo8',
            name='causasDef2I4',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Causas de defunción 2 I (4)'),
        ),
        migrations.AddField(
            model_name='anexo8',
            name='causasDef2II1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Causas de defunción 2 II (1)'),
        ),
        migrations.AddField(
            model_name='anexo8',
            name='causasDef2II2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Causas de defunción 2 II (2)'),
        ),
        migrations.AddField(
            model_name='anexo8',
            name='causasDefI',
            field=models.CharField(default='', max_length=100, verbose_name='Causas de defunción I (1)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anexo8',
            name='causasDefI2',
            field=models.CharField(default='', max_length=100, verbose_name='Causas de defunción I (2)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anexo8',
            name='causasDefI3',
            field=models.CharField(default='', max_length=100, verbose_name='Causas de defunción I (3)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anexo8',
            name='causasDefI4',
            field=models.CharField(default='', max_length=100, verbose_name='Causas de defunción I (4)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anexo8',
            name='causasDefII1',
            field=models.CharField(default='', max_length=100, verbose_name='Causas de defunción II (1)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anexo8',
            name='causasDefII2',
            field=models.CharField(default='', max_length=100, verbose_name='Causas de defunción II (2)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anexo8',
            name='certificadaPor',
            field=models.CharField(choices=[('MEDICO TRATANTE', 'MEDICO TRATANTE'), ('MEDICO LEGISTA', 'MEDICO LEGISTA'), ('OTRO MEDICO', 'OTRO MEDICO'), ('PERSONAL AUTORIZADO POR SS', 'PERSONAL AUTORIZADO POR SS'), ('AUTORIDAD CIVIL', 'AUTORIDAD CIVIL'), ('OTRO', 'OTRO'), ('SE IGNORA', 'SE IGNORA')], default='', max_length=50, verbose_name='Certificada por'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anexo8',
            name='edadAnio',
            field=models.SmallIntegerField(default=0, verbose_name='Edad en Anio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anexo8',
            name='edadDia',
            field=models.SmallIntegerField(default=0, verbose_name='Edad en Dia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anexo8',
            name='edadHora',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Edad en Hora'),
        ),
        migrations.AddField(
            model_name='anexo8',
            name='edadMes',
            field=models.SmallIntegerField(default=0, verbose_name='Edad en Mes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anexo8',
            name='edadMin',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Edad en Minuto'),
        ),
        migrations.AlterField(
            model_name='anexo8',
            name='causaVigEpi2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Causa sujeta a vigilancia epidemiologica 2'),
        ),
        migrations.AlterField(
            model_name='anexo8',
            name='escolaridad',
            field=models.CharField(choices=[('NINGUNA', 'NINGUNA'), ('PRIMARIA INCOMPLETA', 'PRIMARIA INCOMPLETA'), ('SECUNDARIA INCOMPLETA', 'SECUNDARIA INCOMPLETA'), ('BACHILLERATO O PREPARATORIA INCOMPLETA', 'BACHILLERATO O PREPARATORIA INCOMPLETA'), ('PROFESIONAL', 'PROFESIONAL'), ('SE IGNORA', 'SE IGNORA'), ('PRE-ESCOLAR', 'PRE-ESCOLAR'), ('PRIMARIA COMPLETA', 'PRIMARIA COMPLETA'), ('SECUNDARIA COMPLETA', 'SECUNDARIA COMPLETA'), ('BACHILLERATO O PREPARATORIA COMPLETA', 'BACHILLERATO O PREPARATORIA COMPLETA'), ('POSGRADO', 'POSGRADO')], default='', max_length=50, verbose_name='Escolaridad'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='anexo8',
            name='lugarDefEnti',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entidadDef', to='home.entidad', verbose_name='Lugar donde ocurrio la defuncion, Entidad'),
        ),
        migrations.AlterField(
            model_name='anexo8',
            name='lugarDefMuni',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='municipioDef', to='home.municipio', verbose_name='Lugar donde ocurrio la defuncion, Municipio'),
        ),
        migrations.AlterField(
            model_name='anexo8',
            name='lugardeResidenciaEnti',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.entidad', verbose_name='Lugar de residencia habitual, Entidad'),
        ),
        migrations.AlterField(
            model_name='anexo8',
            name='lugardeResidenciaMuni',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.municipio', verbose_name='Lugar de residencia habitual, Municipio'),
        ),
        migrations.AlterField(
            model_name='anexo8',
            name='nombreCertificante',
            field=models.CharField(max_length=30, verbose_name='Nombre del Certificante'),
        ),
        migrations.AlterField(
            model_name='anexo8',
            name='nombreResponsableInv',
            field=models.CharField(default='', max_length=50, verbose_name='Nombre del responsable de la investigación'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='anexo8',
            name='observaciones',
            field=models.TextField(default='', verbose_name='Observaciones'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='anexo8',
            name='ocupacion',
            field=models.CharField(default='', max_length=50, verbose_name='Ocupación'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='anexo8',
            name='ratifica',
            field=models.CharField(choices=[('Ratifica', 'Ratifica'), ('Rectifica', 'Rectifica')], default='', max_length=20, verbose_name='Ratifica'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registroestudio',
            name='edadAnio',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Edad (años)'),
        ),
        migrations.AlterField(
            model_name='registroestudio',
            name='edadDia',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Edad (días)'),
        ),
        migrations.AlterField(
            model_name='registroestudio',
            name='edadMes',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Edad (meses)'),
        ),
    ]
