# Generated by Django 3.2.16 on 2023-05-28 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_alter_paciente_numext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroestudio',
            name='fallecio',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=2, null=True, verbose_name='Fallecio?'),
        ),
        migrations.AlterField(
            model_name='registroestudio',
            name='perdioCaso',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=2, null=True, verbose_name='Se perdio el caso?'),
        ),
        migrations.AlterField(
            model_name='registroestudio',
            name='portador',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=2, null=True, verbose_name='Quedo como portador?'),
        ),
        migrations.AlterField(
            model_name='registroestudio',
            name='reestablecer',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=2, null=True, verbose_name='Se reestablecio integrante?'),
        ),
        migrations.AlterField(
            model_name='registroestudio',
            name='secuelas',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=2, null=True, verbose_name='Quedo secuelas?'),
        ),
    ]
