# Generated by Django 3.2.16 on 2023-05-28 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_auto_20230527_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
