# Generated by Django 3.2.16 on 2023-05-28 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_alter_contacto_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacto',
            old_name='id',
            new_name='idContacto',
        ),
    ]
