# Generated by Django 3.2.16 on 2023-05-28 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_rename_id_contacto_idcontacto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacto',
            old_name='idContacto',
            new_name='id',
        ),
    ]
