# Generated by Django 3.2.16 on 2023-05-28 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_rename_idcontacto_contacto_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anexo8',
            name='causaVigEpiCodigoCie2',
        ),
    ]
